const { RecursiveCharacterTextSplitter } = require('langchain/text_splitter');
const { MemoryVectorStore } = require('langchain/vectorstores/memory');
const { OpenAIEmbeddings, ChatOpenAI } = require('@langchain/openai');
const { OpenAI } = require('openai');

const isApiKeyValid = process.env.OPENAI_API_KEY && 
                     !process.env.OPENAI_API_KEY.startsWith('your_') && 
                     process.env.OPENAI_API_KEY.trim() !== '';

/**
 * Perform QA chat over a document's text using RAG (LangChain + OpenAI or custom keyword fallback)
 * @param {string} rawText The full text of the document
 * @param {string} question The user's query/question
 * @returns {Promise<string>} The answer generated by the LLM (or fallback generator)
 */
const queryDocument = async (rawText, question) => {
  if (!rawText) {
    return "The document does not contain any readable text.";
  }

  // Step 1: Chunk the document
  const splitter = new RecursiveCharacterTextSplitter({
    chunkSize: 1000,
    chunkOverlap: 200,
  });

  const docs = await splitter.createDocuments([rawText]);

  // Step 2: RAG Pipeline
  if (isApiKeyValid) {
    try {
      // Create memory vector store with OpenAI Embeddings
      const embeddings = new OpenAIEmbeddings({
        openAIApiKey: process.env.OPENAI_API_KEY,
      });

      const vectorStore = await MemoryVectorStore.fromDocuments(docs, embeddings);
      
      // Retrieve top 3 relevant chunks
      const relevantDocs = await vectorStore.similaritySearch(question, 3);
      const context = relevantDocs.map(doc => doc.pageContent).join('\n\n');

      // Call OpenAI to generate answer based on context
      const chat = new ChatOpenAI({
        openAIApiKey: process.env.OPENAI_API_KEY,
        modelName: 'gpt-4o-mini',
        temperature: 0,
      });

      const prompt = `You are a helpful legal AI assistant. You have been asked a question about a legal document.
Use the following extracted sections of the document to answer the user's question.
If you cannot find the answer in the provided sections, say "I cannot find the answer in the document context."

Extracted Context:
${context}

User Question: ${question}

Provide a professional, clear, and direct answer based on the context. If referring to a specific clause or section, mention its name/number if visible in the context.`;

      const response = await chat.invoke(prompt);
      return response.content;
    } catch (error) {
      console.error('LangChain RAG Error:', error);
      // Fail over to mock RAG search
      return runFallbackRag(docs, question);
    }
  } else {
    // Return custom mock RAG search
    return runFallbackRag(docs, question);
  }
};

/**
 * Local keyword-matching search and answer synthesizer when API is unavailable.
 */
function runFallbackRag(docs, question) {
  console.log('Running local keyword-matching search fallback for RAG Chat.');

  // Tokenize question
  const questionWords = question.toLowerCase()
    .replace(/[^\w\s]/g, '')
    .split(/\s+/)
    .filter(w => w.length > 2); // filter out short stop words

  if (questionWords.length === 0) {
    return "Could you please specify your question in more detail?";
  }

  // Score each document chunk based on token occurrences
  const scoredDocs = docs.map(doc => {
    const chunkText = doc.pageContent.toLowerCase();
    let score = 0;
    questionWords.forEach(word => {
      if (chunkText.includes(word)) {
        score += 1;
        // Boost score if keyword is near relevant search terms
        if (word === 'termination' || word === 'cancel' || word === 'end') score += 2;
        if (word === 'payment' || word === 'fee' || word === 'price') score += 2;
        if (word === 'liable' || word === 'liability' || word === 'limit') score += 2;
        if (word === 'indemnify' || word === 'indemnity') score += 2;
      }
    });
    return { doc, score };
  });

  // Sort and select top matching chunk
  scoredDocs.sort((a, b) => b.score - a.score);
  const bestMatch = scoredDocs[0];

  if (!bestMatch || bestMatch.score === 0) {
    return "I couldn't find sections in the document that specifically address your query. Could you try rephrasing it or asking about clauses like 'termination', 'indemnification', 'payments', or 'obligations'?";
  }

  // Synthesize answer based on matching chunk text
  const matchText = bestMatch.doc.pageContent;
  
  // Custom rule-based syntheses
  const questionLower = question.toLowerCase();
  let topic = "relevant terms";
  
  if (questionLower.includes('termination') || questionLower.includes('terminate')) {
    topic = "termination and cancellation provisions";
  } else if (questionLower.includes('payment') || questionLower.includes('fee') || questionLower.includes('invoice')) {
    topic = "payment conditions and financial timelines";
  } else if (questionLower.includes('liability') || questionLower.includes('liable') || questionLower.includes('indemnity')) {
    topic = "limit of liability and indemnification terms";
  } else if (questionLower.includes('dispute') || questionLower.includes('arbitration') || questionLower.includes('court')) {
    topic = "dispute resolution and arbitration process";
  }

  return `[Offline AI Mock Mode] Based on the document's sections discussing ${topic}:
  
"... ${matchText.substring(0, 500)} ..."

According to this snippet, the document outlines specific covenants governing this topic. Review the segment above or open the Clause Breakdown section in your dashboard to see how these provisions affect each party's obligations.`;
}

module.exports = { queryDocument };
